HseICalendar/__init__.py
"""
The flask application package.
"""

from flask import Flask


def createApp(iconInstance, personInstance):
    app = Flask(__name__)

    app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0

    from .views import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .settings import settings as settings_blueprint
    app.register_blueprint(settings_blueprint)

    from .proxy import proxy as proxy_blueprint
    app.register_blueprint(proxy_blueprint)

    from .actions import actions as actions_blueprint
    app.register_blueprint(actions_blueprint)

    app.config['ICON'] = iconInstance
    app.config['PERSON'] = personInstance

    app.add_template_global(personInstance, 'Person')

    return app

HseICalendar/views.py
"""
Routes and views for the flask application.
"""

from flask import current_app, render_template, Blueprint, redirect, url_for
from datetime import datetime

main = Blueprint('main', __name__)


@main.route('/')
def index():
    currentPageTitle = "Index"
    lastUpdate = datetime.fromtimestamp(
        int(current_app.config['PERSON'].lastUpdate))\
        .strftime("%d/%m/%Y, %H:%M:%S")
    return render_template('index.html',
                           currentPageTitle=currentPageTitle,
                           syncDate=lastUpdate)

HseICalendar/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>{{ currentPageTitle }}</title>
  <link rel="stylesheet" href="static/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="static/fonts/fontawesome5-overrides.min.css">
  <link rel="stylesheet" href="static/css/styles.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
</head>

<body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="54">
  <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">HSE ICalendar</a><button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">HOME</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('settings.index') }}">SETTINGS</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('actions.forceupdate') }}">FORCE UPDATE</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('actions.clearold') }}">CLEAR OLD</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('actions.toggle') }}">{% if Person.synchronization=="1" %}DISABLE{% else %}ENABLE{% endif %}</a></li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %} {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="static/js/script.min.js"></script>
</body>

</html>

HseICalendar/templates/index.html
{% extends "base.html" %} {% block content %}
<header class="masthead" style="background-image:url('static/img/header-bg.jpg');">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"><span>Service for synchronizing RUZ and another calendars</span></div>
      <div class="intro-lead-in"><span>Last sync was at {{ syncDate }}</span></div>
      <div class="intro-heading text-uppercase"></div><a class="btn btn-primary btn-xl text-uppercase" role="button" href="{{ url_for('settings.index') }}">Settings</a>



    </div>
  </div>
</header>
{% endblock %}

HseICalendar/templates/settings.html
{% extends "base.html" %} {% block content %}
<header class="masthead" style="background-image:url('static/img/header-bg.jpg');">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"><span style="font-size: 22px;">Enter your full name as in RUZ</span></div>
      <div class="intro-heading text-uppercase"></div>
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <div class="card m-auto" style="max-width:850px">
            <div class="card-body">
              <div class="rendered-form">
                <form method="POST" action="{{ url_for('settings.change') }}" class="align-items-center form-control form-control-lg flex-shrink-1 form-control-borderless">
                  <fieldset>

                    <!-- Form Name -->
                    <legend>Settings</legend>

                    <!-- Text input-->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="name">Full name</label>
                      <div>
                        <input type="hidden" id="fullname" name="name" value="{{ Person.name }}">
                        <input type="hidden" id="type" name="type" value="{{ Person.type }}">
                        <select id="name" name="ruzid" class="form-control">
                          <option value="{{ Person.ruzid }}" data-select2-id="{{ Person.ruzid }}">{{ Person.name }}</option>
                        </select>
                      </div>
                    </div>

                    <!-- Select Basic -->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="update">Update every</label>
                      <div>
                        <select id="update" name="update" class="form-control">
                          <option value="0" {% if Person.update=="0" %} selected="selected"{% endif %}>half hour</option>
                          <option value="1" {% if Person.update=="1" %} selected="selected"{% endif %}>hour</option>
                          <option value="2" {% if Person.update=="2" %} selected="selected"{% endif %}>2 hours</option>
                          <option value="3" {% if Person.update=="3" %} selected="selected"{% endif %}>4 hours</option>
                          <option value="4" {% if Person.update=="4" %} selected="selected"{% endif %}>8 hours</option>
                          <option value="5" {% if Person.update=="5" %} selected="selected"{% endif %}>day</option>
                          <option value="6" {% if Person.update=="6" %} selected="selected"{% endif %}>week</option>
                        </select>
                      </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="url">URL</label>
                      <div>
                        <input id="url" name="url" type="text" readonly class="form-control input-md" value="{{ baseURL }}static/schedules/RUZ.ics">
                        <span class="help-block">Paste it to your calendar</span>
                      </div>
                    </div>

                    <!-- Button -->
                    <div class="form-group">
                      <div class="col-md-4">
                        <button id="submit" name="submit" class="btn btn-success">Submit</button>
                      </div>
                    </div>

                  </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<script>
$("#update").select2();
$("#name").select2({
  minimumInputLength: 5,
  ajax: {
    url: "{{ baseURL }}proxy/https://ruz.hse.ru/api/search",
    dataType: 'json',
    delay: 500,
    data: function (params) {
      return {
        term: params.term
      };
    },
    processResults: function (data, params) {

      return {
        results: data
      };
    },
    cache: true
  },
  escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
  templateResult: formatPerson, // omitted for brevity, see the source of this page
  templateSelection: formatPersonSelection // omitted for brevity, see the source of this page
});

function formatPerson (person) {
    var markup = person.label + " (" + person.description + ")";
    return markup;
}

function formatPersonSelection (person) {
    return person.label || person.text;
}

$('#name').on('select2:select', function (e) {
  $('#fullname').attr('value', e.params.data.label);
  $('#type').attr('value', e.params.data.type);
  console.log(e.params.data);
});
</script>
{% endblock %}